"""Add calibration_config to devices

Revision ID: 8a57095d9809
Revises: 9e74e6be75cc
Create Date: 2026-02-01 21:50:23.384837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a57095d9809'
down_revision = '9e74e6be75cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('calibration_config', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'calibration_config')
    # ### end Alembic commands ###
