"""Initial migration

Revision ID: 9e74e6be75cc
Revises: 9c5032d42f9e
Create Date: 2026-02-01 19:57:05.505338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e74e6be75cc'
down_revision = '9c5032d42f9e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
